version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "grandpat"
      POSTGRES_PASSWORD: "grandpat"
#    volumes:
#      - ./data.sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  nats-streaming:
    image: nats-streaming
    ports:
      - '4222:4222'
      - '8222:8222'

